let emoje = [
    { name: 'al',
  type: 'dir',
  content: 
   [ 
     { name: 'ali88new_thumb.gif', type: 'file' },
     { name: 'alibainiannew_thumb.gif', type: 'file' },
     { name: 'alibaoyibaonew_thumb.gif', type: 'file' },
     { name: 'alibianpaonew_thumb.gif', type: 'file' },
     { name: 'alibiechaonew_thumb.gif', type: 'file' },
     { name: 'alibumanew_thumb.gif', type: 'file' },
     { name: 'alibunaifannew_thumb.gif', type: 'file' },
     { name: 'alicainew_thumb.gif', type: 'file' },
     { name: 'alidachinew_thumb.gif', type: 'file' },
     { name: 'alidagunnew_thumb.gif', type: 'file' },
     { name: 'alidalanqiunew_thumb.gif', type: 'file' },
     { name: 'alidesenew_thumb.gif', type: 'file' },
     { name: 'alidiantounew_thumb.gif', type: 'file' },
     { name: 'alidingqinew_thumb.gif', type: 'file' },
     { name: 'alifanbaiyannew_thumb.gif', type: 'file' },
     { name: 'alifeinew_thumb.gif', type: 'file' },
     { name: 'alifengzhengnew_thumb.gif', type: 'file' },
     { name: 'aligongyi_thumb.gif', type: 'file' },
     { name: 'aliguiqiunew_thumb.gif', type: 'file' },
     { name: 'alihuaixiaonew_thumb.gif', type: 'file' },
     { name: 'alihuanhunew_thumb.gif', type: 'file' },
     { name: 'alihuaquanquannew_thumb.gif', type: 'file' },
     { name: 'alihulaquannew_thumb.gif', type: 'file' },
     { name: 'alijiangshitiaonew_thumb.gif', type: 'file' },
     { name: 'alijiayounew_thumb.gif', type: 'file' },
     { name: 'alijingnew_thumb.gif', type: 'file' },
     { name: 'alijiongnew_thumb.gif', type: 'file' },
     { name: 'alilaibanew_thumb.gif', type: 'file' },
     { name: 'alilaipinew_thumb.gif', type: 'file' },
     { name: 'aliliunew_thumb.gif', type: 'file' },
     { name: 'alimomotounew_thumb.gif', type: 'file' },
     { name: 'alinaoqiangnew_thumb.gif', type: 'file' },
     { name: 'alininew_thumb.gif', type: 'file' },
     { name: 'alipaipaishounew_thumb.gif', type: 'file' },
     { name: 'alipengtinew_thumb.gif', type: 'file' },
     { name: 'alipiaoguonew_thumb.gif', type: 'file' },
     { name: 'alipiaonew_thumb.gif', type: 'file' },
     { name: 'alipudaonew_thumb.gif', type: 'file' },
     { name: 'alipunew_thumb.gif', type: 'file' },
     { name: 'aliqianzounew_thumb.gif', type: 'file' },
     { name: 'aliqinyigenew_thumb.gif', type: 'file' },
     { name: 'aliqiunew_thumb.gif', type: 'file' },
     { name: 'alisaqiannew_thumb.gif', type: 'file' },
     { name: 'alishuainew_thumb.gif', type: 'file' },
     { name: 'alishuaishounew_thumb.gif', type: 'file' },
     { name: 'alishuinew_thumb.gif', type: 'file' },
     { name: 'alisongliwunew_thumb.gif', type: 'file' },
     { name: 'alitoukannew_thumb.gif', type: 'file' },
     { name: 'alituxuenew_thumb.gif', type: 'file' },
     { name: 'aliwanew_thumb.gif', type: 'file' },
     { name: 'alixianew_thumb.gif', type: 'file' },
     { name: 'alixiangnew_thumb.gif', type: 'file' },
     { name: 'alixianhuanew_thumb.gif', type: 'file' },
     { name: 'alixianzhuozinew_thumb.gif', type: 'file' },
     { name: 'alixiaonew_thumb.gif', type: 'file' },
     { name: 'alixiaosilenew_thumb.gif', type: 'file' },
     { name: 'alixiunew_thumb.gif', type: 'file' },
     { name: 'alixuxunew_thumb.gif', type: 'file' },
     { name: 'aliyaohuangnew_thumb.gif', type: 'file' },
     { name: 'aliyuanbaonew_thumb.gif', type: 'file' },
     { name: 'aliyumengnew_thumb.gif', type: 'file' },
     { name: 'alizhuannew_thumb.gif', type: 'file' },
     { name: 'alizhuanquankunew_thumb.gif', type: 'file' },
     { name: 'alizhuinew_thumb.gif', type: 'file' },
     { name: 'alizuoguiliannew_thumb.gif', type: 'file' },
     { name: 'j3_thumb.gif', type: 'file' },
     { name: 'm2_thumb.gif', type: 'file' },
     { name: 'mh_thumb.gif', type: 'file' },
     { name: 'newalidese_thumb.gif', type: 'file' },
     { name: 'q2_thumb.gif', type: 'file' },
     { name: 'wq2_thumb.gif', type: 'file' },
     { name: 'zk_thumb.gif', type: 'file' } ] },
     { name: 'ltdren',type: 'dir',content: 
   [ { name: 'dadadenglong_thumb.gif', type: 'file' },
     { name: 'dadayangge_thumb.gif', type: 'file' },
     { name: 'dadazhuanquan_thumb.gif', type: 'file' },
     { name: 'kxlyun_thumb.gif', type: 'file' },
     { name: 'xklbainian_thumb.gif', type: 'file' },
     { name: 'xklbanyun1_thumb.gif', type: 'file' },
     { name: 'xklbanyun2_thumb.gif', type: 'file' },
     { name: 'xklbeidian_thumb.gif', type: 'file' },
     { name: 'xklbeizhua_thumb.gif', type: 'file' },
     { name: 'xklbenpao_thumb.gif', type: 'file' },
     { name: 'xklbianpao_thumb.gif', type: 'file' },
     { name: 'xklchixigua_thumb.gif', type: 'file' },
     { name: 'xkldacha_thumb.gif', type: 'file' },
     { name: 'xkldadaheian_thumb.gif', type: 'file' },
     { name: 'xkldadahuaixiao_thumb.gif', type: 'file' },
     { name: 'xkldadatushetou_thumb.gif', type: 'file' },
     { name: 'xkldadaxihuan_thumb.gif', type: 'file' },
     { name: 'xklding_thumb.gif', type: 'file' },
     { name: 'xklfacai_thumb.gif', type: 'file' },
     { name: 'xklfumo_thumb.gif', type: 'file' },
     { name: 'xklgongxi_thumb.gif', type: 'file' },
     { name: 'xklhahaha_thumb.gif', type: 'file' },
     { name: 'xkljiong_thumb.gif', type: 'file' },
     { name: 'xklkun_thumb.gif', type: 'file' },
     { name: 'xklluguo_thumb.gif', type: 'file' },
     { name: 'xklnielian_thumb.gif', type: 'file' },
     { name: 'xklnipaiyi_thumb.gif', type: 'file' },
     { name: 'xklniu_thumb.gif', type: 'file' },
     { name: 'xklqidai_thumb.gif', type: 'file' },
     { name: 'xklqinqin_thumb.gif', type: 'file' },
     { name: 'xklrengtangdou_thumb.gif', type: 'file' },
     { name: 'xklsahua_thumb.gif', type: 'file' },
     { name: 'xklshihua_thumb.gif', type: 'file' },
     { name: 'xkltangdou_thumb.gif', type: 'file' },
     { name: 'xkltoukan_thumb.gif', type: 'file' },
     { name: 'xklweiqu_thumb.gif', type: 'file' },
     { name: 'xklxi_thumb.gif', type: 'file' },
     { name: 'xklxiaxue_thumb.gif', type: 'file' },
     { name: 'xklyaoweiba_thumb.gif', type: 'file' },
     { name: 'xklyongbao_thumb.gif', type: 'file' },
     { name: 'xklzhayan_thumb.gif', type: 'file' },
     { name: 'xklzhuakuang_thumb.gif', type: 'file' },
     { name: 'xklzhuanquan_thumb.gif', type: 'file' },
     { name: 'xklzhui_thumb.gif', type: 'file' },
     { name: 'xlknuhuo_thumb.gif', type: 'file' } ] },
{ name: 'default',
  type: 'dir',
  content: 
   [ 
     { name: '88_thumb.gif', type: 'file' },
     { name: 'angrya_thumb.gif', type: 'file' },
     { name: 'bba_thumb.gif', type: 'file' },
     { name: 'bs2_thumb.gif', type: 'file' },
     { name: 'bs_thumb.gif', type: 'file' },
     { name: 'buyao_org.gif', type: 'file' },
     { name: 'bz_thumb.gif', type: 'file' },
     { name: 'cakev2_thumb.gif', type: 'file' },
     { name: 'cj_thumb.gif', type: 'file' },
     { name: 'come_thumb.gif', type: 'file' },
     { name: 'cool_thumb.gif', type: 'file' },
     { name: 'crazya_thumb.gif', type: 'file' },
     { name: 'cry.gif', type: 'file' },
     { name: 'cza_thumb.gif', type: 'file' },
     { name: 'dizzya_thumb.gif', type: 'file' },
     { name: 'fuyun_thumb.gif', type: 'file' },
     { name: 'geiliv2_thumb.gif', type: 'file' },
     { name: 'good_thumb.gif', type: 'file' },
     { name: 'gza_thumb.gif', type: 'file' },
     { name: 'h_thumb.gif', type: 'file' },
     { name: 'haqianv2_thumb.gif', type: 'file' },
     { name: 'hatea_thumb.gif', type: 'file' },
     { name: 'hearta_thumb.gif', type: 'file' },
     { name: 'heia_thumb.gif', type: 'file' },
     { name: 'horse2_thumb.gif', type: 'file' },
     { name: 'huanglianse_thumb.gif', type: 'file' },
     { name: 'huangliansj_thumb.gif', type: 'file' },
     { name: 'huanglianwx_thumb.gif', type: 'file' },
     { name: 'huatongv2_thumb.gif', type: 'file' },
     { name: 'hufen_thumb.gif', type: 'file' },
     { name: 'j_thumb.gif', type: 'file' },
     { name: 'kl_thumb.gif', type: 'file' },
     { name: 'kunv2_thumb.gif', type: 'file' },
     { name: 'landeln_thumb.gif', type: 'file' },
     { name: 'laugh.gif', type: 'file' },
     { name: 'lazhuv2_thumb.gif', type: 'file' },
     { name: 'lovea_thumb.gif', type: 'file' },
     { name: 'mb_thumb.gif', type: 'file' },
     { name: 'money_thumb.gif', type: 'file' },
     { name: 'numav2_thumb.gif', type: 'file' },
     { name: 'ok_thumb.gif', type: 'file' },
     { name: 'panda_thumb.gif', type: 'file' },
     { name: 'pcmoren_huaixiao_thumb.png', type: 'file' },
     { name: 'pcmoren_tian_thumb.png', type: 'file' },
     { name: 'pcmoren_wu_thumb.png', type: 'file' },
     { name: 'pig.gif', type: 'file' },
     { name: 'qq_thumb.gif', type: 'file' },
     { name: 'rabbit_thumb.gif', type: 'file' },
     { name: 'sad_thumb.gif', type: 'file' },
     { name: 'sada_thumb.gif', type: 'file' },
     { name: 'sb_thumb.gif', type: 'file' },
     { name: 'shamea_thumb.gif', type: 'file' },
     { name: 'shenshou_thumb.gif', type: 'file' },
     { name: 'sk_thumb.gif', type: 'file' },
     { name: 'sw_thumb.gif', type: 'file' },
     { name: 'sweata_thumb.gif', type: 'file' },
     { name: 't_thumb.gif', type: 'file' },
     { name: 'tootha_thumb.gif', type: 'file' },
     { name: 'tza_thumb.gif', type: 'file' },
     { name: 'unheart.gif', type: 'file' },
     { name: 'vw_thumb.gif', type: 'file' },
     { name: 'wabi_thumb.gif', type: 'file' },
     { name: 'wg_thumb.gif', type: 'file' },
     { name: 'wq_thumb.gif', type: 'file' },
     { name: 'x_thumb.gif', type: 'file' },
     { name: 'ye_thumb.gif', type: 'file' },
     { name: 'yhh_thumb.gif', type: 'file' },
     { name: 'yw_thumb.gif', type: 'file' },
     { name: 'yx_thumb.gif', type: 'file' },
     { name: 'z2_thumb.gif', type: 'file' },
     { name: 'zhh_thumb.gif', type: 'file' },
     { name: 'zy_thumb.gif', type: 'file' } ] },
{ name: 'heart',
  type: 'dir',
  content: 
   [
     { name: '88_thumb (1).gif', type: 'file' },
     { name: 'angrya_thumb (1).gif', type: 'file' },
     { name: 'bad_thumb (1).gif', type: 'file' },
     { name: 'bba_thumb (1).gif', type: 'file' },
     { name: 'bs2_thumb (1).gif', type: 'file' },
     { name: 'bs_thumb (1).gif', type: 'file' },
     { name: 'buyao_org (1).gif', type: 'file' },
     { name: 'bz_thumb (1).gif', type: 'file' },
     { name: 'cj_thumb (1).gif', type: 'file' },
     { name: 'come_thumb (1).gif', type: 'file' },
     { name: 'cool_thumb (1).gif', type: 'file' },
     { name: 'crazya_thumb (1).gif', type: 'file' },
     { name: 'cry (1).gif', type: 'file' },
     { name: 'cza_thumb (1).gif', type: 'file' },
     { name: 'd_thumb (1).gif', type: 'file' },
     { name: 'dalian_thumb (1).gif', type: 'file' },
     { name: 'dizzya_thumb (1).gif', type: 'file' },
     { name: 'fn_thumb (1).gif', type: 'file' },
     { name: 'gm_thumb (1).gif', type: 'file' },
     { name: 'good_thumb (1).gif', type: 'file' },
     { name: 'green_band_thumb (1).gif', type: 'file' },
     { name: 'gza_thumb (1).gif', type: 'file' },
     { name: 'h_thumb (1).gif', type: 'file' },
     { name: 'ha_thumb (1).gif', type: 'file' },
     { name: 'haqianv2_thumb (1).gif', type: 'file' },
     { name: 'hatea_thumb (1).gif', type: 'file' },
     { name: 'hearta_thumb (1).gif', type: 'file' },
     { name: 'heia_thumb (1).gif', type: 'file' },
     { name: 'huanglianse_thumb (1).gif', type: 'file' },
     { name: 'huangliansj_thumb (1).gif', type: 'file' },
     { name: 'huanglianwx_thumb (1).gif', type: 'file' },
     { name: 'kl_thumb (1).gif', type: 'file' },
     { name: 'kunv2_thumb (1).gif', type: 'file' },
     { name: 'landeln_thumb (1).gif', type: 'file' },
     { name: 'laugh (1).gif', type: 'file' },
     { name: 'left_thumb (1).gif', type: 'file' },
     { name: 'lovea_thumb (1).gif', type: 'file' },
     { name: 'lovea_thumb.gif', type: 'file' },
     { name: 'mb_thumb.gif', type: 'file' },
     { name: 'money_thumb (1).gif', type: 'file' },
     { name: 'numav2_thumb (1).gif', type: 'file' },
     { name: 'o_thumb (1).gif', type: 'file' },
     { name: 'ok_thumb (1).gif', type: 'file' },
     { name: 'qq_thumb (1).gif', type: 'file' },
     { name: 'red_band_thumb (1).gif', type: 'file' },
     { name: 'right_thumb (1).gif', type: 'file' },
     { name: 'sad_thumb (1).gif', type: 'file' },
     { name: 'sada_thumb (1).gif', type: 'file' },
     { name: 'sb_thumb (1).gif', type: 'file' },
     { name: 'sdz_thumb (1).gif', type: 'file' },
     { name: 'shamea_thumb (1).gif', type: 'file' },
     { name: 'shayan_thumb (1).gif', type: 'file' },
     { name: 'sk_thumb (1).gif', type: 'file' },
     { name: 'sw_thumb (1).gif', type: 'file' },
     { name: 'sweata_thumb (1).gif', type: 'file' },
     { name: 't_thumb (1).gif', type: 'file' },
     { name: 'tootha_thumb (1).gif', type: 'file' },
     { name: 'tza_thumb (1).gif', type: 'file' },
     { name: 'wabi_thumb (1).gif', type: 'file' },
     { name: 'wq_thumb (1).gif', type: 'file' },
     { name: 'ws_thumb (1).gif', type: 'file' },
     { name: 'x_thumb (1).gif', type: 'file' },
     { name: 'xiaoku_thumb (1).gif', type: 'file' },
     { name: 'ye_thumb (1).gif', type: 'file' },
     { name: 'yhh_thumb (1).gif', type: 'file' },
     { name: 'yw_thumb (1).gif', type: 'file' },
     { name: 'yx_thumb (1).gif', type: 'file' },
     { name: 'z2_thumb (1).gif', type: 'file' },
     { name: 'zhh_thumb.gif', type: 'file' },
     { name: 'zuoyi_thumb (1).gif', type: 'file' },
     { name: 'zy_thumb (1).gif', type: 'file' } ] },
{ name: 'ltu',
  type: 'dir',
  content: 
   [
     { name: 'lehaqian_thumb.gif', type: 'file' },
     { name: 'ltbengfeng_thumb.gif', type: 'file' },
     { name: 'ltbixue_thumb.gif', type: 'file' },
     { name: 'ltchuipaopao_thumb.gif', type: 'file' },
     { name: 'ltchuoxia_thumb.gif', type: 'file' },
     { name: 'ltdanteng_thumb.gif', type: 'file' },
     { name: 'ltding_thumb.gif', type: 'file' },
     { name: 'lteating_thumb.gif', type: 'file' },
     { name: 'lterduo_thumb.gif', type: 'file' },
     { name: 'ltfankun_thumb.gif', type: 'file' },
     { name: 'ltfuyun_thumb.gif', type: 'file' },
     { name: 'ltgangnamstyle_thumb.gif', type: 'file' },
     { name: 'ltgood_thumb.gif', type: 'file' },
     { name: 'lthalloween_thumb.gif', type: 'file' },
     { name: 'ltheixian_thumb.gif', type: 'file' },
     { name: 'lthongbao_thumb.gif', type: 'file' },
     { name: 'lthuifeiyanmie_thumb.gif', type: 'file' },
     { name: 'ltjingxia_thumb.gif', type: 'file' },
     { name: 'ltjiong_thumb.gif', type: 'file' },
     { name: 'ltjuhan_thumb.gif', type: 'file' },
     { name: 'ltlei_thumb.gif', type: 'file' },
     { name: 'ltleimu_thumb.gif', type: 'file' },
     { name: 'ltmuqinjie_thumb.gif', type: 'file' },
     { name: 'ltpaishou_thumb.gif', type: 'file' },
     { name: 'ltpaizhuodaxiao_thumb.gif', type: 'file' },
     { name: 'ltpen_thumb.gif', type: 'file' },
     { name: 'ltpenxue_thumb.gif', type: 'file' },
     { name: 'ltqianshui_thumb.gif', type: 'file' },
     { name: 'ltqiekenao_thumb.gif', type: 'file' },
     { name: 'ltrock_thumb.gif', type: 'file' },
     { name: 'ltsahua_thumb.gif', type: 'file' },
     { name: 'ltshanxia_thumb.gif', type: 'file' },
     { name: 'lttickets_thumb.gif', type: 'file' },
     { name: 'lttoukui_thumb.gif', type: 'file' },
     { name: 'lttrain_thumb.gif', type: 'file' },
     { name: 'lttu_thumb.gif', type: 'file' },
     { name: 'ltwabi_thumb.gif', type: 'file' },
     { name: 'ltwuyi_thumb.gif', type: 'file' },
     { name: 'ltxia_thumb.gif', type: 'file' },
     { name: 'ltxiaohua_thumb.gif', type: 'file' },
     { name: 'ltxinnianhao_thumb.gif', type: 'file' },
     { name: 'ltxiu_thumb.gif', type: 'file' },
     { name: 'ltxue_thumb.gif', type: 'file' },
     { name: 'ltyaobai_thumb.gif', type: 'file' },
     { name: 'ltyihuo_thumb.gif', type: 'file' },
     { name: 'ltyinxian_thumb.gif', type: 'file' },
     { name: 'ltzhongqiang_thumb.gif', type: 'file' },
     { name: 'ltzhuanfa_thumb.gif', type: 'file' },
     { name: 'ltzuiyou_thumb.gif', type: 'file' } ] }
]

export default { emoje }